'use client';

/**
 * 3D ring of hero clips for the marketing LP.
 *
 * Performance contract — the ring renders 10 vertical clips around a Y-axis rotation. Before this
 * file was rewritten, every panel mounted with `preload="metadata" autoplay`, so the browser
 * downloaded all 10 moov atoms in parallel and spun up 10 video decoders. That accounted for
 * ~13 MB of payload and ~1 s of TBT on the LP (per Lighthouse 2026-05-11).
 *
 * The new strategy:
 *
 *   1. Every panel ships a JPEG poster (~15-25 KB each, generated by
 *      tools/optimize-studio-videos.mjs into /public/studio/posters). The ring is fully populated
 *      visually on first paint with ~170 KB of total poster overhead.
 *   2. Each <video> mounts with `preload="none"` — no network until we say so.
 *   3. A lightweight rotation tracker computes which panels are currently within ±100° of front.
 *      Only those panels are told to start loading (`preload="metadata"`) and play; back-facing
 *      panels stay paused with their poster. As the ring spins, panels rotate in/out of the
 *      active window so all 10 will have warmed up after ~36 s, but never more than ~6
 *      concurrently — the browser's HTTP/2 head-of-line queue never gets saturated.
 *   4. `prefers-reduced-motion` keeps the ring frozen (handled in the CSS); the JS just picks the
 *      panels statically visible in the frozen pose.
 *
 * Net effect: initial LP payload drops by 12-13 MB and the GPU only decodes ~5 videos at a time
 * instead of 10.
 */

import { useEffect, useRef } from 'react';
import type { CSSProperties, SyntheticEvent } from 'react';
import styles from './HeroVideoCarousel3D.module.css';

const DEFAULT_SRCS = [
  '/studio/0328(1).mp4',
  '/studio/0328(2).mp4',
  '/studio/0328(3).mp4',
  '/studio/0328(4).mp4',
  '/studio/0328(5).mp4',
  '/studio/0328(6).mp4',
  '/studio/0328(7).mp4',
  '/studio/0328(8).mp4',
  '/studio/0328(9).mp4',
  '/studio/0328(10).mp4',
];

/** 10 clips, ~36° apart, about 5 readable in view; no duplicate `<video>` URLs. */
const MAX_UNIQUE_SRCS = 10;
/** CSS sets `animation: heroSpin 36s linear infinite` on `.ring`. Mirror it here. */
const RING_FULL_TURN_MS = 36_000;
/** Static angle of `.ring` when prefers-reduced-motion is on (matches the CSS rule). */
const REDUCED_MOTION_RING_ANGLE_DEG = -22;
/**
 * A panel counts as "front" when its effective angle (panel base + ring rotation) is within
 * ±100° of zero. Slightly more than ±90° to give a small overlap so the boundary swap doesn't
 * flicker mid-rotation.
 */
const FRONT_HALF_ANGLE_DEG = 100;
/** How often we re-evaluate which panels are front. 250 ms is invisible to the eye at this radius. */
const ROTATION_SAMPLE_MS = 250;

type Props = { srcs?: readonly string[] };

/** Replace `0328(N).mp4` with `posters/0328(N).jpg`. Falls back to undefined for unknown paths. */
function srcToPosterUrl(src: string): string | undefined {
  const match = src.match(/^(.*\/)([^/]+)\.mp4$/i);
  if (!match) return undefined;
  const [, dir, base] = match;
  return `${dir}posters/${base}.jpg`;
}

/** Normalise an arbitrary degree value into the (-180, 180] range. */
function normaliseDegrees(deg: number): number {
  const mod = ((deg % 360) + 360) % 360;
  return mod > 180 ? mod - 360 : mod;
}

export function HeroVideoCarousel3D({ srcs = DEFAULT_SRCS }: Props) {
  const rootRef = useRef<HTMLDivElement>(null);
  const list = (srcs.length ? srcs : DEFAULT_SRCS).slice(0, MAX_UNIQUE_SRCS);
  const slice = 360 / list.length;

  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    const videos = Array.from(root.querySelectorAll<HTMLVideoElement>('video'));
    if (videos.length === 0) return;

    // Cache each video's base angle once. Math.round avoids float drift between renders.
    const panelAngles = videos.map((video) => {
      const raw = Number(video.dataset.angle ?? '0');
      return Number.isFinite(raw) ? raw : 0;
    });

    for (const video of videos) {
      // Belt-and-braces: re-assert the muted/playsInline attributes that some Android browsers
      // strip when the element is detached/reattached during hydration.
      video.muted = true;
      video.defaultMuted = true;
      video.playsInline = true;
      video.setAttribute('muted', '');
      video.setAttribute('playsinline', '');
      video.setAttribute('webkit-playsinline', '');
    }

    const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const startTimeMs = Date.now();
    let running = false;
    let intervalId: number | null = null;

    /** Returns the ring's current rotation around Y in degrees (matches the CSS animation). */
    const ringRotationDeg = (): number => {
      if (prefersReducedMotion) return REDUCED_MOTION_RING_ANGLE_DEG;
      const elapsed = Date.now() - startTimeMs;
      // CSS does `0deg → -360deg` over 36 s, so subtract.
      return -((elapsed / RING_FULL_TURN_MS) * 360);
    };

    const isFront = (panelAngleDeg: number): boolean => {
      const eff = normaliseDegrees(panelAngleDeg + ringRotationDeg());
      return Math.abs(eff) <= FRONT_HALF_ANGLE_DEG;
    };

    /** Bump a paused/idle <video> into playing once it's allowed to load. */
    const playSafely = (v: HTMLVideoElement) => {
      const promise = v.play();
      if (promise && typeof promise.catch === 'function') promise.catch(() => {});
    };

    const sync = () => {
      if (document.visibilityState !== 'visible') return;
      for (let i = 0; i < videos.length; i++) {
        const v = videos[i]!;
        const front = isFront(panelAngles[i]!);
        if (front) {
          if (v.preload === 'none') v.preload = 'metadata';
          if (v.paused) playSafely(v);
        } else {
          if (!v.paused) v.pause();
        }
      }
    };

    const pauseAll = () => {
      for (const v of videos) {
        if (!v.paused) v.pause();
      }
    };

    const start = () => {
      if (running) return;
      running = true;
      sync();
      if (intervalId !== null) clearInterval(intervalId);
      intervalId = window.setInterval(sync, ROTATION_SAMPLE_MS);
    };

    const stop = () => {
      running = false;
      if (intervalId !== null) {
        clearInterval(intervalId);
        intervalId = null;
      }
      pauseAll();
    };

    // Start when the ring is anywhere near the viewport; stop when scrolled away.
    const io = new IntersectionObserver(
      ([entry]) => {
        if (entry && entry.isIntersecting) start();
        else stop();
      },
      { root: null, rootMargin: '120px 0px', threshold: 0 },
    );
    io.observe(root);

    // First-paint kick: if the ring is already in view, start immediately rather than waiting
    // for the next IO callback (which can be 100-200 ms late).
    const rect = root.getBoundingClientRect();
    if (rect.top < window.innerHeight && rect.bottom > 0) start();

    const onVisibilityChange = () => {
      if (document.visibilityState !== 'visible') pauseAll();
      else if (running) sync();
    };
    document.addEventListener('visibilitychange', onVisibilityChange);

    /**
     * Mobile Safari/Chrome can block autoplay until a user gesture. Retry on the first
     * touch/pointer interaction anywhere in the carousel so the ring isn't stuck on posters.
     */
    const retryOnGesture = () => {
      if (running) sync();
    };
    root.addEventListener('touchstart', retryOnGesture, { passive: true });
    root.addEventListener('pointerdown', retryOnGesture, { passive: true });
    root.addEventListener('click', retryOnGesture, { passive: true });

    return () => {
      io.disconnect();
      stop();
      document.removeEventListener('visibilitychange', onVisibilityChange);
      root.removeEventListener('touchstart', retryOnGesture);
      root.removeEventListener('pointerdown', retryOnGesture);
      root.removeEventListener('click', retryOnGesture);
    };
  }, []);

  const handleEnded = (e: SyntheticEvent<HTMLVideoElement>) => {
    const v = e.currentTarget;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    if (document.visibilityState !== 'visible') return;
    v.currentTime = 0;
    const p = v.play();
    if (p && typeof p.catch === 'function') p.catch(() => {});
  };

  /** If playback resumes near the end of the loop, rewind first. */
  const handlePlay = (e: SyntheticEvent<HTMLVideoElement>) => {
    const v = e.currentTarget;
    const d = v.duration;
    if (d && Number.isFinite(d) && v.currentTime >= d - 0.08) v.currentTime = 0;
  };

  if (!list.length) return null;

  const panels = list.map((src, i) => ({
    src,
    angle: slice * i,
    poster: srcToPosterUrl(src),
  }));

  return (
    <div ref={rootRef} className={styles.root} aria-hidden>
      <div className={styles.scene}>
        <div className={styles.ring}>
          {panels.map(({ src, angle, poster }, i) => (
            <div
              key={i}
              className={styles.panel}
              style={{ '--angle': `${angle}deg` } as CSSProperties}
            >
              {/*
                preload="none" + no `autoPlay` attribute: the effect above flips preload to
                "metadata" and calls play() once the panel rotates into the front half. Before
                that the poster JPEG is what the user sees.
              */}
              <video
                className={styles.video}
                src={src}
                poster={poster}
                data-angle={angle}
                muted
                loop
                playsInline
                controls={false}
                preload="none"
                disableRemotePlayback
                disablePictureInPicture
                onEnded={handleEnded}
                onPlay={handlePlay}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
